Repository aliyun/aliyun-tsdb-java-sdk, pull requests merged in 2020-09, with the labels that each got.

#53 Write asynchronous interface supports incoming `Collection<Point>` collection, aligned with synchronous write interface function
  src/main/java/com/aliyun/hitsdb/client/BalTSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/TSDB.java
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
Labels: enhancement

#54 Support httpSocketTimeout and httpConnectionRequestTimeout configurations
  src/main/java/com/aliyun/hitsdb/client/AbstractConfig.java
  src/main/java/com/aliyun/hitsdb/client/Config.java
  src/main/java/com/aliyun/hitsdb/client/HiTSDBConfig.java
  src/main/java/com/aliyun/hitsdb/client/TSDBConfig.java
  src/main/java/com/aliyun/hitsdb/client/http/HttpClientFactory.java
  src/test/java/com/aliyun/hitsdb/client/configuration/TestConfiguration.java
Labels: enhancement

#60 Support hint feature
  src/main/java/com/aliyun/hitsdb/client/value/request/LastPointQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/LastPointSubQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/MultiFieldQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/MultiFieldSubQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/Query.java
  src/main/java/com/aliyun/hitsdb/client/value/request/SubQuery.java
  src/test/java/com/aliyun/hitsdb/client/TestHiTSDBClientQuery.java
Labels: feature

#67 Fix QueryResult dps timestamp order
  src/main/java/com/aliyun/hitsdb/client/value/response/QueryResultDpsSerializer.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestMultiFieldQueryResult.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestQueryResult.java
Labels: bug

#68 Support flush method
  src/main/java/com/aliyun/hitsdb/client/BalTSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/TSDB.java
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/queue/DataPointQueue.java
  src/main/java/com/aliyun/hitsdb/client/queue/DataQueue.java
  src/test/java/com/aliyun/hitsdb/client/FlushTest.java
Labels: feature
