Repository aliyun/aliyun-tsdb-java-sdk, pull requests merged in 2021-02, with the labels that each got.

#98 the leak of semaphore
  src/main/java/com/aliyun/hitsdb/client/callback/http/BatchPutHttpResponseCallback.java
  src/main/java/com/aliyun/hitsdb/client/callback/http/MultiFieldBatchPutHttpResponseCallback.java
Labels: bug

#104 fix ignore errors call back bugs for put/mput
  src/main/java/com/aliyun/hitsdb/client/consumer/BatchPutRunnable.java
  src/main/java/com/aliyun/hitsdb/client/consumer/MultiFieldBatchPutRunnable.java
Labels: bug

#66 Add GeoPointValue and GeoIntersects filter type
  src/main/java/com/aliyun/hitsdb/client/util/WKTParser.java
  src/main/java/com/aliyun/hitsdb/client/value/request/ByteArrayValue.java
  src/main/java/com/aliyun/hitsdb/client/value/request/ComplexValue.java
  src/main/java/com/aliyun/hitsdb/client/value/request/FieldsSerializer.java
  src/main/java/com/aliyun/hitsdb/client/value/request/GeoPointValue.java
  src/main/java/com/aliyun/hitsdb/client/value/request/MultiFieldSubQueryDetails.java
  src/main/java/com/aliyun/hitsdb/client/value/request/SubQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/ValueSerializer.java
  src/main/java/com/aliyun/hitsdb/client/value/response/MultiFieldQueryValuesSerializer.java
  src/main/java/com/aliyun/hitsdb/client/value/response/QueryResultDpsSerializer.java
  src/main/java/com/aliyun/hitsdb/client/value/type/FilterType.java
  src/test/java/com/aliyun/hitsdb/client/value/TestQuery.java
  src/test/java/com/aliyun/hitsdb/client/value/request/FilterTest.java
  src/test/java/com/aliyun/hitsdb/client/value/request/MultiPointTest.java
  src/test/java/com/aliyun/hitsdb/client/value/request/PointTest.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestMultiFieldQueryResult.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestQueryResult.java
Labels: feature

#108 adjust the range of unit test for travis-ci
  .travis.yml
Labels: build

#106 QueryHAPolicy
  src/main/java/com/aliyun/hitsdb/client/AbstractConfig.java
  src/main/java/com/aliyun/hitsdb/client/Config.java
  src/main/java/com/aliyun/hitsdb/client/HAPolicy.java
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/TSDBConfig.java
  src/main/java/com/aliyun/hitsdb/client/TSDBHAClient.java
  src/test/java/com/aliyun/hitsdb/client/TestClientQueryHA.java
Labels: feature

#107 unique points
  src/main/java/com/aliyun/hitsdb/client/AbstractConfig.java
  src/main/java/com/aliyun/hitsdb/client/Config.java
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/TSDBConfig.java
  src/main/java/com/aliyun/hitsdb/client/consumer/BatchPutRunnable.java
  src/main/java/com/aliyun/hitsdb/client/consumer/MultiFieldBatchPutRunnable.java
  src/main/java/com/aliyun/hitsdb/client/value/request/UniqueUtil.java
  src/test/java/com/aliyun/hitsdb/client/value/request/UniqueUtilTest.java
Labels: enhancement
