Repository aliyun/aliyun-tsdb-java-sdk, pull requests merged in 2021-07, with the labels that each got.

#127 fix retry logic missing database info
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/callback/http/BatchPutHttpResponseCallback.java
  src/main/java/com/aliyun/hitsdb/client/callback/http/MultiFieldBatchPutHttpResponseCallback.java
  src/main/java/com/aliyun/hitsdb/client/http/HttpClient.java
Labels: bug

#129 fix the inconsistent behaviors of the result class for putSync() and multiFieldPutSync()
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestPutMPutResult.java
Labels: bug

#131 modify the deployment configurations according to the OSSRH
  pom.xml
Labels: build

#132 fix the case of retry limit reached
  src/main/java/com/aliyun/hitsdb/client/callback/http/BatchPutHttpResponseCallback.java
  src/main/java/com/aliyun/hitsdb/client/callback/http/MultiFieldBatchPutHttpResponseCallback.java
Labels: bug

#130 add the unit tests for result type of put & mput
  pom.xml
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/test/java/com/aliyun/hitsdb/client/value/response/TestPutMPutResult.java
Labels: unit test

#134 fix the case of retry limit reached
  src/main/java/com/aliyun/hitsdb/client/callback/http/BatchPutHttpResponseCallback.java
  src/main/java/com/aliyun/hitsdb/client/callback/http/MultiFieldBatchPutHttpResponseCallback.java
Labels: bug

#136 fix the known issues
  pom.xml
  src/main/java/com/aliyun/hitsdb/client/AbstractConfig.java
  src/main/java/com/aliyun/hitsdb/client/TSDBConfig.java
  src/test/java/com/aliyun/hitsdb/client/TestClientQueryHA.java
  src/test/java/com/aliyun/hitsdb/client/value/TestConfig.java
Labels: bug, build
