Repository aliyun/aliyun-tsdb-java-sdk, pull requests merged in 2021-04, with the labels that each got.

#116 remove the dependency on javafx.util.Pair to #115
  src/main/java/com/aliyun/hitsdb/client/HAPolicy.java
  src/main/java/com/aliyun/hitsdb/client/util/Pair.java
  src/main/java/com/aliyun/hitsdb/client/value/response/MultiFieldQueryValuesSerializer.java
Labels: bug, dependencies

#120 add the api usage check with de.thetaphi.forbiddenapis to #115
  codestyle/forbidden-apis.txt
  pom.xml
Labels: build, enhancement

#119 change valid lower timestamp to 4294968
  src/main/java/com/aliyun/hitsdb/client/value/request/AbstractPoint.java
  src/main/java/com/aliyun/hitsdb/client/value/request/MultiFieldQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/Query.java
  src/test/java/com/aliyun/hitsdb/client/value/request/UniqueUtilTest.java
Labels: bug

#118 support set type for Lindorm TSDB
  src/main/java/com/aliyun/hitsdb/client/TSDBClient.java
  src/main/java/com/aliyun/hitsdb/client/value/request/LastPointQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/MultiFieldQuery.java
  src/main/java/com/aliyun/hitsdb/client/value/request/Query.java
  src/main/java/com/aliyun/hitsdb/client/value/type/QueryType.java
  src/test/java/com/aliyun/hitsdb/client/value/request/LastPointQueryTest.java
  src/test/java/com/aliyun/hitsdb/client/value/request/QueryTest.java
Labels: feature
